import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import Footer from "./ui/footer";
import Header from "./ui/header";
import { obterSessaoSeValida } from "./lib/session";

import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';

export const metadata: Metadata = {
  title: "Ranking de jogos",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const sessao = await obterSessaoSeValida()

  return (
    <html lang="en">
      <body>
        <Header sessao={sessao} />
        {children}
        <Footer />
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
